Cpr molleweide
bevry/dorothy pull request #111
Opened 2022-01-14 18:39 UTC by molleweide

2022-01-14 18:47 UTC, molleweide commented
what is your opinion on using `&&` for creating tight if checks.
if you look at this script: https://github.com/LukeSmithxyz/LARBS/blob/master/larbs.sh

2022-01-15 02:18 UTC, balupton commented
It's common in other scripts, but is not something Dorothy does. It is obtuse, and makes modifications such as more conditions or more conditional commands more convoluted.

If the Dorothy style guide doesn't mention this, then it should be updated.

2022-01-15 03:12 UTC, balupton requested changes
will merge typo

2022-01-15 03:12 UTC, balupton commented on commands/cpr
> +	command-exists cp    && tools+=(cp)
It's common outside Dorothy, but it is not something Dorothy does. It is obtuse (it mixes and matches the roles of conditionals and actions, making groking a more involved process, especially for beginners), and makes modifications such as more conditions and more conditional commands more convoluted.

If bash ever had a linter rewriter (such as prettier.io for other ecosystems), I'd imagine such keystroke shortcut statements would get automatically converted into the expanded if statement upon save as the linter does its rewrites.

Refer to the style guide at https://github.com/bevry/dorothy/discussions/46

2022-01-15 03:12 UTC, balupton commented on commands/cpr
> +	#   --owner, -o: preserve owner (super-user only)
👍

2022-01-15 03:26 UTC, balupton commented
Merged the typo fix: https://github.com/bevry/dorothy/commit/c4fab2afee221dcf42b9b376ce10b44320193274

Will update the style guide to be more detailed on the `condition && action` subject.

2022-01-15 03:26 UTC, closed without merging